[workspace]
resolver = "2"
members = [
    "pod-api",
    "pod-code",
    "pod-compiler",
    "pod-loader",
    "pod-preload",
    "pod-guest",
    "pod-host",
    "pod-v2-api",
    "pod-v2-code",
    "pod-v2-compiler",
    "pod-v2-runtime",
    "pod-v2-host",
    "pod-v2-types",
    "pod-v2-derive",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
libc = "0.2.174"
pod-api = { path = "pod-api" }
pod-loader = { path = "pod-loader" }
pod-v2-api = { path = "pod-v2-api" }
pod-v2-runtime = { path = "pod-v2-runtime" }
pod-v2-types = { path = "pod-v2-types" }
sha2 = "0.10.9"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
