[package]
name = "rpc-serde-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
detcore = { package = "hermit-detcore", git = "https://github.com/rrnewton/hermit.git", rev = "75506005d873a76f62be00b1d82696188651047a" }
reverie = { package = "reverie-core", git = "https://github.com/rrnewton/reverie.git", rev = "0ae0c01b5e4c9fbf85c97adc66c2740f280727df" }
serde = "1.0.219"
serde_json = "1.0.140"
