#!/bin/bash
# Install the PATH shim herdr-run needs to reach ci-hub.
#
# WHY A SHIM AT ALL: herdr-run resolves programs as BARE NAMES from PATH -- it
# refuses a path argument ("program must be a bare command name"). A symlink
# does not work either: ci-hub is a rust-script and resolves
# `mod history_queries;` relative to the script's own path, so a link makes it
# look for <linkdir>/lib/ and fail to compile.
#
# WHY THE NAME IS `ci-hub-cli` AND NOT `ci-hub`: herdr-run executes in the
# PARENT repo, which contains a `ci-hub/` DIRECTORY. When the shim goes missing,
# the bare name `ci-hub` resolves to that directory and exec fails with
# "cannot execute: Is a directory" -- and in at least one observed case the
# command produced NO OUTPUT AT ALL, which an unwary caller reads as a clean
# empty result rather than a broken query. A name with no directory of the same
# name cannot be shadowed, so the failure mode is removed rather than handled.
#
# Idempotent. Run it if `ci-hub-cli` is missing from PATH.
set -euo pipefail
BIN_DIR="${1:-$HOME/orc-bin}"
TARGET="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/ci-hub/ci-hub"
[ -x "$TARGET" ] || { echo "ci-hub not executable at $TARGET" >&2; exit 1; }
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/ci-hub-cli" <<SHIM
#!/bin/bash
# Generated by scripts/install-ci-hub-shim.sh -- do not edit by hand.
exec "$TARGET" "\$@"
SHIM
chmod +x "$BIN_DIR/ci-hub-cli"
echo "installed: $BIN_DIR/ci-hub-cli -> $TARGET"
